### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by near2542**

### CODE REVIEW

**Comment by youoo437** [comment]
wtf

**Comment by youoo437** [comment]
test

**Comment by youoo437** [comment]
spon

**Comment by NapoLionia** [comment]
wtestf

**Comment by MongkonKhumpo** [comment]
Test

**Comment by near2542** [comment]
999

**Comment by youoo437** [comment]
UP down left right ABAB start+menu

**Comment by MongkonKhumpo** [comment]
⬆️⬆️⬇️⬇️⬅️➡️⬅️➡️ B A

**Pull request merged**
